apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"