apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restapi
  name: restapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - image: pdidit1/middleware
        name: restapi
        ports:
        - containerPort: 3000

        
        resources:
          limits:
            memory: "20Mi"
            cpu: "250m"
