apiVersion: v1
kind: Service
metadata:
  name: restapi
  labels:
    apps: restapi
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: restapi
  selector:
    app: restapi